from constants.sys_manage_constants import CREATE, DELETE, DOWNLOAD, EXEC, IMPORT, MODIFY, QUERY, checkAuth, operateAuth

POLICY = {
    "Log": {
        checkAuth: {
            ("/syslog/views/search/", "POST", QUERY, "v4.0"),
            ("/syslog/suggest/", "POST", QUERY, "v4.5"),
            (r"/syslog/views/search/(?P<id>.+?)/execute/", "POST", QUERY, "v4.0"),
            ("/syslog/views/fields/", "GET", QUERY, "v4.0"),
            ("/syslog/views/fields/", "POST", QUERY, "v4.0"),
            ("/syslog/view_detail/(?P<id>.+?)/", "GET", QUERY, "v4.4"),
            ("/syslog/search/saved/", "GET", QUERY, "v4.0"),
            ("/syslog/create_views/", "POST", CREATE, "v4.0"),
            (r"/syslog/delete_views/(?P<id>.+?)/", "DELETE", DELETE, "v4.0"),
            (r"/syslog/update_views/(?P<id>.+?)/", "PUT", MODIFY, "v4.0"),
            (r"/syslog/create_import_job/(?P<searchId>.+?)/(?P<searchTypeId>.+?)/", "POST", CREATE, "v4.0"),
            (r"/syslog/download_files/(?P<exportJobId>.+?)/(?P<filename>.+?)/", "GET", DOWNLOAD, "v4.0"),
            ("/syslog/stream/user_streams/", "GET", QUERY, "v4.4"),
            (r"/syslog/view_condition/(?P<id>.+?)", "GET", QUERY, "v4.5"),
            (r"/syslog/log_clustering/", "POST", QUERY, "v4.7"),
        },
        operateAuth: {},
    },
    "DataReceive": {
        checkAuth: {
            ("/syslog/system/cluster/nodes/", "GET", QUERY, "v4.0"),
            ("/syslog/system/inputs/types/all/", "GET", QUERY, "v4.0"),
            ("/syslog/system/inputs/", "GET", QUERY, "v4.0"),
            (r"/syslog/system/inputs/(?P<inputId>.+?)/", "GET", QUERY, "v4.0"),
            ("/syslog/cluster/inputstates/", "GET", QUERY, "v4.0"),
            ("/syslog/cluster/metrics/multiple/", "POST", QUERY, "v4.0"),
            ("/syslog/tools/contains_string_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/tools/regex_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/tools/grok_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/tools/json_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/stream/relative/", "GET", QUERY, "v4.4"),
            ("/syslog/tools/regex_replace_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/tools/split_and_index_tester/", "POST", EXEC, "v4.4"),
            ("/syslog/tools/substring_tester/", "POST", EXEC, "v4.4"),
            (r"/syslog/extractors/(?P<id>.+?)/", "GET", QUERY, "v4.4"),
            ("/syslog/tools/grok/", "GET", QUERY, "v4.4"),
            ("/syslog/tools/locales/", "GET", QUERY, "v4.4"),
            (r"/syslog/extractor_detail/(?P<id>.+?)/(?P<ex_id>.+?)/", "GET", QUERY, "v4.4"),
        },
        operateAuth: {
            ("/syslog/system/inputs/", "POST", CREATE, "v4.0"),
            (r"/syslog/system/inputs/(?P<inputId>.+?)/", "PUT", MODIFY, "v4.0"),
            (r"/syslog/system/inputs/(?P<inputId>.+?)/", "DELETE", DELETE, "v4.0"),
            (r"/syslog/system/inputs/(?P<inputId>.+?)/staticfields/", "POST", CREATE, "v4.0"),
            (r"/syslog/system/inputs/(?P<inputId>.+?)/staticfields/(?P<key>.+?)/", "DELETE", DELETE, "v4.0"),
            (r"/syslog/cluster/inputstates/(?P<inputId>.+?)/", "PUT", EXEC, "v4.0"),
            (r"/syslog/cluster/inputstates/(?P<inputId>.+?)/", "DELETE", EXEC, "v4.0"),
            (r"/syslog/del_extractor/(?P<id>.+?)/(?P<ex_id>.+?)/", "DELETE", DELETE, "v4.4"),
            (r"/syslog/update_extractor/(?P<id>.+?)/(?P<ex_id>.+?)/", "PUT", MODIFY, "v4.4"),
            (r"/syslog/add_extractors/(?P<id>.+?)/", "POST", CREATE, "v4.4"),
            (r"/syslog/order_extractors/(?P<id>.+?)/", "POST", EXEC, "v4.4"),
            ("/syslog/import/", "POST", IMPORT, "v4.5"),
        },
    },
    "LogMonitor": {
        checkAuth: {
            ("/syslog/events/definitions/", "GET", QUERY, "v4.1"),
            (r"/syslog/events/definitions/(?P<definitionId>[^/]+)/", "GET", QUERY, "v4.1"),
            ("/syslog/events/entity_types/", "GET", QUERY, "v4.3"),
        },
        operateAuth: {
            ("/syslog/events/definitions/", "POST", CREATE, "v4.1"),
            (r"/syslog/events/definitions/(?P<definitionId>[^/]+)/", "PUT", MODIFY, "v4.1"),
            (r"/syslog/events/definitions/(?P<definitionId>[^/]+)/", "DELETE", DELETE, "v4.1"),
            (r"/syslog/events/definitions/(?P<definitionId>.+?)/schedule/", "PUT", EXEC, "v4.1"),
            (r"/syslog/events/definitions/(?P<definitionId>.+?)/unschedule/", "PUT", EXEC, "v4.1"),
            ("/syslog/events/definitions/batch_schedule/", "PUT", EXEC, "v4.1"),
            ("/syslog/events/definitions/batch_unschedule/", "PUT", EXEC, "v4.1"),
            (r"/syslog/del_extractor/(?P<id>.+?)/(?P<ex_id>.+?)/", "DELETE", DELETE, "v4.4"),
        },
    },
    "LogNode": {
        checkAuth: {
            ("/syslog/probe/host/", "POST", QUERY, "v4.2"),
            ("/syslog/probe/node/list/", "POST", QUERY, "v4.2"),
            ("/syslog/probe/list/", "GET", QUERY, "v4.2"),
            ("/syslog/probe/install_steps/", "POST", QUERY, "v4.6"),
            ("/syslog/probe/search_sidecar/", "POST", QUERY, "v4.6"),
        },
        operateAuth: {
            ("/syslog/probe/node/create/", "POST", CREATE, "v4.2"),
            ("/syslog/probe/sidecar/action/", "POST", EXEC, "v4.2"),
            ("/syslog/probe/action/", "POST", EXEC, "v4.2"),
        },
    },
    # 日志管理-采集配置
    "CollectionConfig": {
        checkAuth: {
            ("/syslog/collectors_config/nodes/", "POST", QUERY, "v4.2"),
            ("/syslog/collectors_config/get_use_nodes/", "POST", QUERY, "v4.2"),
            ("/syslog/collectors_config/get_configurations/", "POST", QUERY, "v4.2"),
            (r"/syslog/collectors_config/configurations/(?P<configurations_id>\w+)/", "GET", QUERY, "v4.2"),
        },
        operateAuth: {
            ("/syslog/collectors_config/configurations/", "POST", CREATE, "v4.2"),
            ("/syslog/collectors_config/copy_configurations/", "POST", CREATE, "v4.2"),
            ("/syslog/collectors_config/associative_configuration/", "POST", MODIFY, "v4.2"),
            ("/syslog/collectors_config/update_configurations/", "PUT", MODIFY, "v4.2"),
            (r"/syslog/collectors_config/(?P<configurations_id>\w+)/configurations/", "DELETE", MODIFY, "v4.2"),
        },
    },
    # 数据流
    "LogGroup": {
        checkAuth: {
            ("/syslog/stream/paginated/", "GET", QUERY, "v4.4"),
            (r"/syslog/stream/detail/(?P<id>.+?)/", "GET", QUERY, "v4.4"),
            (r"/syslog/stream/rule_types/(?P<id>.+?)/", "GET", QUERY, "v4.4"),
            ("/syslog/stream/relative/", "GET", QUERY, "v4.4"),
            (r"/syslog/stream/rule_detail/(?P<id>.+?)/(?P<rule_id>.+?)/", "GET", QUERY, "v4.4"),
            ("/syslog/stream/system_fields/", "GET", QUERY, "v4.4"),
            ("/syslog/stream/index_sets/", "GET", QUERY, "v4.4"),
            ("/syslog/stream/system_inputs/", "GET", QUERY, "v4.4"),
        },
        operateAuth: {
            ("/syslog/stream/create/", "POST", CREATE, "v4.4"),
            (r"/syslog/stream/update/(?P<id>.+?)/", "PUT", MODIFY, "v4.4"),
            (r"/syslog/stream/delete/(?P<id>.+?)/", "DELETE", DELETE, "v4.4"),
            (r"/syslog/stream/clone/(?P<id>.+?)/", "POST", CREATE, "v4.4"),
            (r"/syslog/stream/test_match/(?P<id>.+?)/", "POST", EXEC, "v4.4"),
            (r"/syslog/stream/add_rules/(?P<id>.+?)/", "POST", CREATE, "v4.4"),
            (r"/syslog/stream/del_rule/(?P<id>.+?)/(?P<rule_id>.+?)/", "DELETE", DELETE, "v4.4"),
            (r"/syslog/stream/update_rule/(?P<id>.+?)/(?P<rule_id>.+?)/", "PUT", MODIFY, "v4.4"),
            (r"/syslog/stream/role_streams/(?P<role_id>.+?)/", "GET", QUERY, "v4.4"),
            (r"/syslog/stream/role_streams/(?P<role_id>.+?)/", "POST", MODIFY, "v4.4"),
        },
    },
    # 日志索引
    "IndexSet": {
        checkAuth: {
            ("/syslog/stream/index_sets/", "GET", QUERY, "v4.5"),
            (r"/syslog/index/index_set/(?P<id>.+?)/", "GET", QUERY, "v4.5"),
            (r"/syslog/index/index_set_overview/(?P<id>.+?)/", "GET", QUERY, "v4.5"),
            (r"/syslog/index/index_list/(?P<id>.+?)/", "GET", QUERY, "v4.5"),
            ("/syslog/index/indexs_multiple/", "POST", QUERY, "v4.5"),
            ("/syslog/index/index_sets_stats/", "GET", QUERY, "v4.5"),
        },
        operateAuth: {
            (r"/syslog/index/default/(?P<id>.+?)/", "PUT", EXEC, "v4.5"),
            (r"/syslog/index/delete/(?P<id>.+?)/", "DELETE", DELETE, "v4.5"),
            (r"/syslog/index/create/", "POST", CREATE, "v4.5"),
            (r"/syslog/index/update/(?P<id>.+?)/", "PUT", MODIFY, "v4.5"),
            (r"/syslog/index/index_set_rebuild/(?P<id>.+?)/", "POST", EXEC, "v4.5"),
            (r"/syslog/index/create_index/(?P<id>.+?)/", "POST", CREATE, "v4.5"),
            (r"/syslog/index/index_rebuild/(?P<index_name>.+?)/", "POST", EXEC, "v4.5"),
            (r"/syslog/index/index_reopen/(?P<index_name>.+?)/", "POST", EXEC, "v4.5"),
            (r"/syslog/index/index_close/(?P<index_name>.+?)/", "POST", EXEC, "v4.5"),
            (r"/syslog/index/index_delete/(?P<index_name>.+?)/", "DELETE", EXEC, "v4.5"),
        },
    },
}
