# Generated by Django 2.2.6 on 2023-06-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syslog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("node_name", models.CharField(default="", help_text="节点名称", max_length=200, unique=True)),
                ("bk_host_id", models.IntegerField(default=0, help_text="实例ID", unique=True)),
            ],
            options={
                "verbose_name": "探针节点",
            },
        ),
        migrations.CreateModel(
            name="ProbeJob",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("probe_type", models.CharField(default="", help_text="探针类型", max_length=100)),
                ("action", models.CharField(default="", help_text="操作", max_length=100)),
                ("job_id", models.BigIntegerField(db_index=True, default=0, help_text="作业实例ID")),
                ("job_code", models.SmallIntegerField(db_index=True, default=0, help_text="作业状态码")),
                ("message", models.TextField(default={}, help_text="message")),
                (
                    "node",
                    models.ForeignKey(help_text="探针ID", on_delete=django.db.models.deletion.CASCADE, to="syslog.Node"),
                ),
            ],
            options={
                "verbose_name": "探针任务",
            },
        ),
    ]
