# Generated by Django 2.2.6 on 2023-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syslog", "0003_auto_20230726_1722"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("id", models.CharField(help_text="数据流ID", max_length=100, primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, help_text="数据流标题", max_length=200)),
            ],
            options={
                "verbose_name": "数据流",
            },
        ),
    ]
