# Generated by Django 2.2.6 on 2023-08-14 16:07

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syslog", "0004_stream"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleStream",
            fields=[
                ("role_id", models.IntegerField(help_text="角色ID", primary_key=True, serialize=False)),
                ("stream_list", django_mysql.models.JSONField(default=list, help_text="数据流列表")),
            ],
        ),
    ]
