# Generated by Django 2.2.6 on 2023-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syslog", "0005_rolestream"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_manual",
            field=models.BooleanField(default=False, help_text="是否手动"),
        ),
    ]
