# Generated by Django 2.2.6 on 2023-12-20 17:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('menu_name', models.CharField(help_text='菜单名称', max_length=64, unique=True)),
                ('default', models.BooleanField(default=False, help_text='是否是内置菜单')),
                ('use', models.BooleanField(default=False, help_text='是否启用(只能有一个)')),
                ('menu', django.contrib.postgres.fields.jsonb.JSONField(help_text='菜单内容')),
            ],
            options={
                'verbose_name': '菜单管理',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(db_index=True, max_length=128, null=True)),
                ('operate_type', models.CharField(choices=[('add', '新增'), ('modify', '修改'), ('exec', '执行'), ('delete', '删除'), ('download', '下载'), ('upload', '上传'), ('login', '登陆')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='添加时间')),
                ('operate_obj', models.CharField(db_index=True, default='', max_length=200)),
                ('operate_summary', models.TextField(default='')),
                ('current_ip', models.CharField(db_index=True, default='127.0.0.1', max_length=50)),
                ('app_module', models.CharField(db_index=True, default='', max_length=20)),
                ('obj_type', models.CharField(db_index=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': '使用记录',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('role_name', models.CharField(max_length=128, unique=True, verbose_name='角色名称')),
                ('describe', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='角色描述')),
                ('built_in', models.BooleanField(default=False, verbose_name='是否内置(内置不允许修改)')),
            ],
            options={
                'verbose_name': '系统角色',
            },
        ),
        migrations.CreateModel(
            name='SysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('vtype', models.CharField(default='string', max_length=32, verbose_name='类型')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置项')),
                ('value', models.TextField(verbose_name='设置值')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='设置描述')),
            ],
            options={
                'verbose_name': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('bk_user_id', models.SmallIntegerField(default=0, verbose_name='用户id(用户管理处的id)')),
                ('bk_username', models.CharField(max_length=128, unique=True, verbose_name='用户名称')),
                ('chname', models.CharField(default='', max_length=128, verbose_name='中文名称')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱地址')),
                ('sexuality', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('wx_userid', models.CharField(default='', max_length=200, verbose_name='微信openId')),
                ('local', models.BooleanField(default=True, verbose_name='是否为默认目录用户')),
                ('departments', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='组织架构')),
                ('leader', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='上级')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('DISABLED', '禁用')], default='NORMAL', max_length=32, verbose_name='用户状态')),
                ('roles', models.ManyToManyField(to='system_mgmt.SysRole', verbose_name='角色')),
            ],
            options={
                'verbose_name': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='UserSysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('vtype', models.CharField(default='string', max_length=32, verbose_name='类型')),
                ('key', models.CharField(max_length=100, verbose_name='key值')),
                ('value', models.TextField(default='', verbose_name='系统设置值')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='system_mgmt.SysUser')),
            ],
            options={
                'verbose_name': '用户系统设置',
            },
        ),
        migrations.CreateModel(
            name='SysApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('app_name', models.CharField(max_length=128, verbose_name='资源名称')),
                ('app_key', models.CharField(max_length=64, verbose_name='资源标识')),
                ('app_ids', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='资源列表')),
                ('sys_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_mgmt.SysRole')),
            ],
            options={
                'verbose_name': '角色资源',
            },
        ),
        migrations.CreateModel(
            name='InstancesPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('instance_type', models.CharField(help_text='实例类型', max_length=64)),
                ('permissions', django.contrib.postgres.fields.jsonb.JSONField(help_text='权限类型')),
                ('instances', django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='实例id')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_mgmt.SysRole')),
            ],
            options={
                'verbose_name': '时间相关字段',
                'abstract': False,
            },
        ),
    ]
